// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// ignore: depend_on_referenced_packages
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCS8v_UFceQw9VF8Jwra6qElc8Us6jFbaw',
    appId: '1:672681777331:web:f29ea31c94cc54673478c6',
    messagingSenderId: '672681777331',
    projectId: 'movie-search-5042a',
    authDomain: 'movie-search-5042a.firebaseapp.com',
    storageBucket: 'movie-search-5042a.appspot.com',
    measurementId: 'G-RGXDJ1CPS5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHh01PcQRYDyj3ADCfohSpsVtduoodmtE',
    appId: '1:134363696646:android:05bb0fe5cbccab361a7d87',
    messagingSenderId: '134363696646',
    projectId: 'exper-1ff6f',
    storageBucket: 'exper-1ff6f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGtJNMgOGTIFAO2S3lMJwK4u28NWr5e9U',
    appId: '1:672681777331:ios:20834eec51f2f7443478c6',
    messagingSenderId: '672681777331',
    projectId: 'movie-search-5042a',
    storageBucket: 'movie-search-5042a.appspot.com',
    iosBundleId: 'com.example.movieSearch',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGtJNMgOGTIFAO2S3lMJwK4u28NWr5e9U',
    appId: '1:672681777331:ios:b8d1f4b887054a4e3478c6',
    messagingSenderId: '672681777331',
    projectId: 'movie-search-5042a',
    storageBucket: 'movie-search-5042a.appspot.com',
    iosBundleId: 'com.example.movieSearch.RunnerTests',
  );
}
